name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build 
      run: |
        docker build . -t shubhammore/webhook:latest
    - name: docker push
      run: |
        docker push shubhammore/webhook:latest
